### ISSUE TITLE
Add user has non-hashed plain text version of password

### ISSUE THREAD

**Issue by eweisner1973** [inputlogic/django-api-starter#41]
Solution in other projects was to use custom form:
add_form = UserAdminCreateForm (see Step-Up for example)

**Comment by weslord** [comment]
Related: #48

**Comment by weslord** [comment]
I cannot reproduce this in a fresh install of django-api-starter.

Looking in Step-Up at the commit which introduced `UserAdminCreateForm` (21b3c114), the problem there was caused by the previously-used custom form `UserAdminForm`, which was specific to Step-Up and is not used in django-api-starter.
